apiVersion: v1
entries:
  aws-cdk-operator:
  - apiVersion: v2
    appVersion: v0.0.104
    created: "2025-08-01T11:55:07.985534+12:00"
    description: A Kubernetes operator for managing AWS CDK TypeScript stacks via
      Git integration
    digest: 1822791c1bb58259fd23630657d529d4ae53ba34fe02da0c7ac3cafb52f03a75
    name: aws-cdk-operator
    type: application
    urls:
    - https://awscdk.dev/charts/aws-cdk-operator-0.0.104.tgz
    version: 0.0.104
generated: "2025-08-01T11:55:07.985039+12:00"
